# Generated by Django 3.0.3 on 2022-07-13 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('contactNo', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, default=main.models.get_default_profile_image, max_length=255, null=True, upload_to=main.models.get_profile_image_filepath)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
