# Generated by Django 3.0.3 on 2022-07-21 05:55

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('category', models.CharField(choices=[('FOOD', 'FOOD'), ('COMMUNITY', 'COMMUNITY'), ('SPORTS', 'SPORTS'), ('FESTIVAL', 'FESTIVAL')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('neighbourhood', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, default=main.models.get_default_event_image, max_length=255, null=True, upload_to=main.models.get_event_image_filepath)),
            ],
        ),
    ]
