# Generated by Django 3.0.3 on 2022-07-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='UserEvent',
        ),
    ]
