# Generated by Django 4.1 on 2022-08-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20220726_0635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevent",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOOD", "Food"),
                    ("COMMUNITY", "Community"),
                    ("SPORTS", "Sports & Exercise"),
                    ("FESTIVAL", "Festival"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
            ),
        ),
    ]
