# Generated by Django 4.1 on 2022-08-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_userevent_neighbourhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="attendees", to="main.userprofile"
            ),
        ),
    ]
