# Generated by Django 4.1 on 2022-08-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_rename_time_userevent_end_time_userevent_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="location",
            field=models.CharField(default="Limbang Park, 680784", max_length=100),
            preserve_default=False,
        ),
    ]
